# Common configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      client:
        url: http://localhost:8085

# Service-specific configurations
api-gateway:
  server:
    port: 8090

dashboard-service:
  server:
    port: 8083
  spring:
    datasource:
      url: jdbc:h2:mem:dashboarddb
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

order-service:
  server:
    port: 8082
  spring:
    datasource:
      url: jdbc:h2:mem:orderdb
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

product-service:
  server:
    port: 8081
  spring:
    datasource:
      url: jdbc:h2:mem:productdb
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

eureka-server:
  server:
    port: 8761