version: '3.8'

services:
  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    volumes:
      - ./eureka-server/target/eureka-server-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && java -jar /app/app.jar"]
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net

  config-server:
    image: openjdk:17-jdk-slim
    container_name: config-server
    volumes:
      - ./config-server/target/config-server-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 30 && java -jar /app/app.jar"]
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

  admin-server:
    image: openjdk:17-jdk-slim
    container_name: admin-server
    volumes:
      - ./admin-server/target/admin-server-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 60 && java -jar /app/app.jar"]
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

  api-gateway:
    image: openjdk:17-jdk-slim
    container_name: api-gateway
    volumes:
      - ./api-gateway/target/api-gateway-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 90 && java -jar /app/app.jar"]
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL-INTERVAL=3000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-INTERVAL=10000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS=20
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

  product-service:
    image: openjdk:17-jdk-slim
    container_name: product-service
    volumes:
      - ./product-service/target/product-service-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 120 && java -jar /app/app.jar"]
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL-INTERVAL=3000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-INTERVAL=10000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS=20
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

  order-service:
    image: openjdk:17-jdk-slim
    container_name: order-service
    volumes:
      - ./order-service/target/order-service-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 150 && java -jar /app/app.jar"]
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL-INTERVAL=3000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-INTERVAL=10000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS=20
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

  dashboard-service:
    image: openjdk:17-jdk-slim
    container_name: dashboard-service
    volumes:
      - ./dashboard-service/target/dashboard-service-1.0-SNAPSHOT.jar:/app/app.jar
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep 180 && java -jar /app/app.jar"]
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL-INTERVAL=3000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-INTERVAL=10000
      - SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS=20
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge