server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wtek01/crossdata-config-repo.git
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          # Use your GitHub PAT here
          # If using SSH, configure private key access instead

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
